OrchidOs : settings cleanup and build fixes
OrchidOs : settings cleanup

This reverts commit dae447483b0fe3ed94f173deb2b936b828d676bb.
Revert "Update awaken_styles.xml"
This reverts commit 72329d9264260fb2594202024b4652be49f3eaf5.

Update top_level_settings.xml
Update dimens.xml
Update top_level_settings.xml

error

Themes.java:51: error: cannot find symbol
    private SystemSettingListPreference mSettingsDashBoardGms;
            ^
  symbol:   class SystemSettingListPreference
  location: class Themes

Update colors.xml

buid error

buid error

packages/apps/Settings/res/values/dimens.xml:499: error: duplicate value for resource 'dimen/op_control_icon_size_indicator' with config ''.
packages/apps/Settings/res/values/dimens.xml:499: error: resource previously defined here.
packages/apps/Settings/res/values/dimens.xml: error: file failed to compile.
packages/apps/Settings/res/values/strings.xml:32: error: duplicate value for resource 'string/storage_warning_internal' with config ''.
packages/apps/Settings/res/values/strings.xml:32: error: resource previously defined here.
packages/apps/Settings/res/values/strings.xml: error: file failed to compile.

build fixes